### ISSUE TITLE
broken with ubuntu latest 16.04.1 LTS

### ISSUE THREAD

**Issue by keeslouwen** [swined/super-couscous#1]
Hello, thanks for your work and Dockerfile. With Ubuntu 15.10 it works fine. With Ubuntu 16.04.1 LTS (latest) xrdp seems to be broken. I do see some remarks on this via google, but didn't have the time myself yet to sort out. Thought I just let you know. 

thanks again! regards, Kees

**Comment by swined** [comment]
Thanks for the report! I've sorted things out with 16.04, but 16.10 does not seem to work yet. Check out the 1610 branch.
